version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
    - nix-bin
  tools:
    python: latest
  jobs:
    build:
      html:
        - nix --store ./nix --extra-experimental-features "nix-command flakes" build -L 'github:epics-extensions/EPNix#docs'
        - mkdir -p $READTHEDOCS_OUTPUT
        - cp -rT "./nix/$(readlink result)/share/doc/epnix/html" $READTHEDOCS_OUTPUT/html
